apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app.kubernetes.io/name: my-app
spec:
  selector:
    app.kubernetes.io/name: my-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
